Fix to use older Rake which has `last_comment` method
Avoid this error:

> NoMethodError: undefined method `last_comment' for #<Rake::Application:0x007fb4a3ba0888>